-- 음식 종류별 GROUPBY 후 가장 많은 즐찾 추출

WITH MAX_FAVORITE AS (
SELECT FOOD_TYPE,
MAX(FAVORITES) AS MAX_FAV
FROM REST_INFO
GROUP BY FOOD_TYPE)

SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, MF.MAX_FAV AS FAVORITES
FROM REST_INFO RI JOIN MAX_FAVORITE MF
ON RI.FOOD_TYPE = MF.FOOD_TYPE
AND RI.FAVORITES = MF.MAX_FAV
ORDER BY RI.FOOD_TYPE DESC;